// <auto-generated />
using System;
using Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace SchoolAPI.Migrations
{
    [DbContext(typeof(RepositoryContext))]
    [Migration("20210717230248_DatabaseCreation")]
    partial class DatabaseCreation
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.8")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Entities.Models.CourseAssignment", b =>
                {
                    b.Property<string>("ca_title")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("CourseSectioncs_id")
                        .HasColumnType("int");

                    b.Property<string>("ca_description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("course_id")
                        .HasColumnType("int");

                    b.Property<int>("cs_id")
                        .HasColumnType("int");

                    b.HasKey("ca_title");

                    b.HasIndex("CourseSectioncs_id");

                    b.ToTable("CourseAssignments");
                });

            modelBuilder.Entity("Entities.Models.CourseSection", b =>
                {
                    b.Property<int>("cs_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("course_id")
                        .HasColumnType("int");

                    b.Property<DateTime>("cs_create_date")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("cs_end_date")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("cs_start_date")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("cs_update_date")
                        .HasColumnType("datetime2");

                    b.HasKey("cs_id");

                    b.ToTable("CourseSections");
                });

            modelBuilder.Entity("Entities.Models.Courses", b =>
                {
                    b.Property<int>("course_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("course_created_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("course_description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("course_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("course_updated_date")
                        .HasColumnType("datetime2");

                    b.HasKey("course_id");

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("Entities.Models.SectionEnroll", b =>
                {
                    b.Property<int>("cs_id")
                        .HasColumnType("int");

                    b.Property<DateTime>("se_created_date")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("se_end_date")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("se_start_date")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("se_updated_date")
                        .HasColumnType("datetime2");

                    b.Property<int>("user_id")
                        .HasColumnType("int");

                    b.ToTable("SectionEnrolls");
                });

            modelBuilder.Entity("Entities.Models.Users", b =>
                {
                    b.Property<int>("user_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("created_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("enroll_status")
                        .HasColumnType("int");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("sys_role_id")
                        .HasColumnType("int");

                    b.Property<DateTime>("updated_date")
                        .HasColumnType("datetime2");

                    b.HasKey("user_id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Entities.Models.CourseAssignment", b =>
                {
                    b.HasOne("Entities.Models.CourseSection", null)
                        .WithMany("courseAssignments")
                        .HasForeignKey("CourseSectioncs_id");
                });

            modelBuilder.Entity("Entities.Models.CourseSection", b =>
                {
                    b.Navigation("courseAssignments");
                });
#pragma warning restore 612, 618
        }
    }
}
